#!/usr/bin/env bash

cat <<'EOF'
#!/usr/bin/env bash
source /usr/local/etc/library.sh
set -eu

! is_app_enabled memories || ncc config:app:set --value="256 4096" previewgenerator coverWidthHeightSizes

for _ in $(seq 1 $(nproc)); do
  ncc preview:generate-all -n -q &
done

wait
EOF