#!/bin/bash

# NextCloudPi software configuration
# Tested with 2017-01-11-raspbian-jessie.img (and lite)
#
# Copyleft 2017 by Ignacio Nunez Hernanz <nacho _a_t_ ownyourbits _d_o_t_ com>
# GPL licensed (see end of file) * Use at your own risk!
#
# Usage:
#   sudo nextcloudpi-config
#
# More at https://ownyourbits.com/2017/03/13/nextcloudpi-gets-nextcloudpi-config/
#

CONFDIR=/usr/local/etc/nextcloudpi-config.d/

source $CONFDIR/library

function nextcloud-config()
{
  local DIALOG_OK=0
  local LIST=()
  for item in $CONFDIR/*.sh; do
    local DESC=$( grep "DESCRIPTION=" $item | sed 's|^DESCRIPTION="||;s|"$||' )
    LIST+=( $( basename $item .sh ) "$DESC" )
  done
  local script
  script=$( whiptail --backtitle "NextCloudPi configuration" \
                     --title "NextCloudPi Software Configuration Tool (nextcloudpi-config)" \
                     --cancel-button Finish --ok-button Select \
                     --menu "Select program to configure and activate:" 20 100 10 \
                     "${LIST[@]}" \
            3>&1 1>&2 2>&3 )

  [[ $? -ne $DIALOG_OK ]] || [[ "$script" == "" ]] && return 1

  (
    cd $CONFDIR
    config $script.sh || return 1                 # writes "$INSTALLATION_CODE"
    echo -e "$INSTALLATION_CODE" > $script.sh     # save configuration
    source ./$script.sh                           # load configuration
    set +x
    configure
  )
}

if [ $(id -u) -ne 0 ]; then
  printf "Must be run as root. Try 'sudo $0'\n"
  exit 1
fi

nextcloud-config

# License
#
# This script is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA  02111-1307  USA
