#!/usr/bin/env bash

cat <<'EOF'
#!/usr/bin/env bash
set -eu
source /usr/local/etc/library.sh

if is_app_enabled memories
then
  ncc config:app:set --value="256 4096" previewgenerator coverWidthHeightSizes
else
  ncc config:app:set --value="" previewgenerator coverWidthHeightSizes
fi

for _ in $(seq 1 $(nproc)); do
  ncc preview:generate-all -n -q &
done

wait
EOF