#!/bin/bash

source /usr/local/etc/library.sh

# INIT NCP CONFIG (first run)
persistent_cfg /usr/local/etc/nextcloudpi-config.d /data/ncp
persistent_cfg /etc/services-enabled.d
persistent_cfg /etc/passwd  # persist ncp-web password

exit 0
