#!/bin/bash

source /usr/local/etc/library.sh

# INIT NCP CONFIG (first run)
persistent_cfg /usr/local/etc/ncp-config.d /data/ncp
persistent_cfg /etc/services-enabled.d
persistent_cfg /etc/letsencrypt/live               # persist SSL certificates
# TODO
persistent_cfg /etc/shadow                         # persist ncp-web password

exit 0
