<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'OCA\\PreviewGenerator\\AppInfo\\Application' => $baseDir . '/../lib/AppInfo/Application.php',
    'OCA\\PreviewGenerator\\Command\\DeleteOld' => $baseDir . '/../lib/Command/DeleteOld.php',
    'OCA\\PreviewGenerator\\Command\\Generate' => $baseDir . '/../lib/Command/Generate.php',
    'OCA\\PreviewGenerator\\Command\\PreGenerate' => $baseDir . '/../lib/Command/PreGenerate.php',
    'OCA\\PreviewGenerator\\Command\\TimestampFormatter' => $baseDir . '/../lib/Command/TimestampFormatter.php',
    'OCA\\PreviewGenerator\\Migration\\Version020000Date20180823071939' => $baseDir . '/../lib/Migration/Version020000Date20180823071939.php',
    'OCA\\PreviewGenerator\\Migration\\Version020200Date20190608205303' => $baseDir . '/../lib/Migration/Version020200Date20190608205303.php',
    'OCA\\PreviewGenerator\\SizeHelper' => $baseDir . '/../lib/SizeHelper.php',
    'OCA\\PreviewGenerator\\Watcher' => $baseDir . '/../lib/Watcher.php',
);
