#!/bin/bash

# Enable static IP or DHCP for Raspbian
#
# Copyleft 2017 by Ignacio Nunez Hernanz <nacho _a_t_ ownyourbits _d_o_t_ com>
# GPL licensed (see end of file) * Use at your own risk!
#
# Usage:
# 
#   ./installer.sh nc-static-IP.sh <IP> (<img>)
#
# See installer.sh instructions for details
# More at: https://ownyourbits.com
#

ACTIVE_=no
IP_=192.168.1.130

DESCRIPTION="Set up a static IP address (on), or DHCP (off)"

configure() 
{
  # delete NCP config
  grep -q "^# NextCloudPi autogenerated" /etc/dhcpcd.conf && \
    sed -i '/^# NextCloudPi autogenerated/,+6d' /etc/dhcpcd.conf

  [[ $ACTIVE_ != "yes" ]] && {
    systemctl restart dhcpcd
    echo "DHCP enabled"
    return
  }

  local GW="$( ip r | grep "default via"   | awk '{ print $3 }' )"
  local DNS="$( grep nameserver /etc/resolv.conf | head -1 | awk '{ print $2 }' )"

  [[ "$DNS" == "" ]] && DNS="$GW"

  cat >> /etc/dhcpcd.conf <<EOF
# NextCloudPi autogenerated
# don't modify! better use nextcloudpi-config
interface eth0
static ip_address=$IP_/24
static routers=$GW
static domain_name_servers=$DNS
EOF

  systemctl restart dhcpcd
  sudo -u www-data php occ config:system:set trusted_domains 1 --value="$IP_"
  sudo -u www-data php occ config:system:set overwrite.cli.url --value=https://"$IP_"
  echo "Static IP set to $IP_"
}

install() { :; }
cleanup() { :; }

# License
#
# This script is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this script; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA  02111-1307  USA

