<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitPreviewGenerator
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\PreviewGenerator\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\PreviewGenerator\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'OCA\\PreviewGenerator\\AppInfo\\Application' => __DIR__ . '/..' . '/../lib/AppInfo/Application.php',
        'OCA\\PreviewGenerator\\Command\\DeleteOld' => __DIR__ . '/..' . '/../lib/Command/DeleteOld.php',
        'OCA\\PreviewGenerator\\Command\\Generate' => __DIR__ . '/..' . '/../lib/Command/Generate.php',
        'OCA\\PreviewGenerator\\Command\\PreGenerate' => __DIR__ . '/..' . '/../lib/Command/PreGenerate.php',
        'OCA\\PreviewGenerator\\Command\\TimestampFormatter' => __DIR__ . '/..' . '/../lib/Command/TimestampFormatter.php',
        'OCA\\PreviewGenerator\\Migration\\Version020000Date20180823071939' => __DIR__ . '/..' . '/../lib/Migration/Version020000Date20180823071939.php',
        'OCA\\PreviewGenerator\\Migration\\Version020200Date20190608205303' => __DIR__ . '/..' . '/../lib/Migration/Version020200Date20190608205303.php',
        'OCA\\PreviewGenerator\\SizeHelper' => __DIR__ . '/..' . '/../lib/SizeHelper.php',
        'OCA\\PreviewGenerator\\Watcher' => __DIR__ . '/..' . '/../lib/Watcher.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitPreviewGenerator::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitPreviewGenerator::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitPreviewGenerator::$classMap;

        }, null, ClassLoader::class);
    }
}
