name: 'NCP Installation Tests'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: git ref, branch or tag to test against
        required: false
        type: string
  push:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: thecalcaholic/ncp-test-automation:latest
      env:
        SSH_PUBLIC_KEY: "${{ secrets.TEST_AUTOMATION_SSH_PUBLIC_KEY }}"
        SSH_PRIVATE_KEY: "${{ secrets.TEST_AUTOMATION_SSH_PRIVATE_KEY }}"
        HCLOUD_TOKEN: "${{ secrets.TEST_AUTOMATION_HCLOUD_API_TOKEN }}"
    env:
      GIT_REF: "${{ github.event.inputs.tag || github.ref_name || github.head_ref }}"
    steps:
      - name: Install and run tests
        run: |
          set -x
          cd /ncp-test-automation/bin
          export HOME="/root"
          echo "Test ping cmd"
          ping -c 1 -w 5 1.1.1.1
          bash /ncp-test-automation/bin/entrypoint.sh
          export SSH_PRIVATE_KEY_PATH="/root/.ssh/automation_ssh_key"
          eval $(ssh-agent)
          ssh-add "$SSH_PRIVATE_KEY_PATH"
          bash /ncp-test-automation/bin/ncp-install-test.sh "${GIT_REF}"


